# Generated by Django 4.0.6 on 2023-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=50)),
                ('vechicle_type', models.CharField(max_length=100)),
                ('vechicle_model', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
    ]
